author:
  name: Christopher Robinson
  url: 'http://christopherrobinson.com'
title: ''
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: ''
color:
  saturation: 0.2062289596069604
  brandStrength: 0.9813658662606031
  rhythmicContrast: 0.4334342344664037
  brandColors:
    - '#F3F5F2'
    - '#A8A8A0'
    - '#191814'
    - '#CA0810'
    - '#5E5D59'
  lightness: 0.8764805982355028
typography_spectrum: 0.2479206852149218
navigation:
  - name: Now
    id: f7c86f45-37da-4daa-8247-c9a65d778bdb
    type: content
  - name: About
    id: 65632b74-adee-404e-bbba-7d4b37aa6996
    type: content
  - name: Services
    id: 03f93665-e4e1-458f-9935-8da286fe7916
    type: content
  - name: Contact
    id: 60283b96-880d-4f31-9973-312e51229c11
    type: content
analytics:
  google: (UA-7031605-2)
layout_spectrum: 0.3028674
name: Christopher Robinson
