typography_spectrum: 0.1091125919483602
color:
  brandStrength: 0.2548510155174881
  lightness: 0.7417863681912422
  saturation: 0.2825960770715028
  rhythmicContrast: 0.35178294451907277
  brandColors:
    - '#F8F9FC'
    - '#224FAA'
    - '#A62626'
    - '#3D588F'
    - '#C7CAD1'
layout_spectrum: 0.6385564166121185
analytics:
  google: (UA-7031605-2)
author:
  name: Christopher Robinson
  url: 'http://christopherrobinson.com'
name: Christopher Robinson
navigation:
  - name: Services
    id: 03f93665-e4e1-458f-9935-8da286fe7916
    type: content
  - name: Now
    id: f7c86f45-37da-4daa-8247-c9a65d778bdb
    type: content
title: Howdy World!
description: 'First drive on The Grid, Woohoo!'
