layout_spectrum: 0.8571102949790657
typography_spectrum: 0.7619490474462509
color:
  saturation: 0.24104893789626658
  brandStrength: 0.15159711544401944
  rhythmicContrast: 0.1408480175305158
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  lightness: 0.48676396789960563
author:
  name: Christopher Robinson
  url: 'http://christopherrobinson.com'
title: ''
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: ''
navigation:
  - name: Now
    id: f7c86f45-37da-4daa-8247-c9a65d778bdb
    type: content
  - name: About
    id: 65632b74-adee-404e-bbba-7d4b37aa6996
    type: content
  - name: Services
    id: 03f93665-e4e1-458f-9935-8da286fe7916
    type: content
  - name: Contact
    id: 60283b96-880d-4f31-9973-312e51229c11
    type: content
analytics:
  google: (UA-7031605-2)
name: Christopher Robinson
